# Package source for sharing: strip git/IDE/build/large files and sanitize secrets.
# Run from repo root:
#   .\scripts\package-for-share.ps1
#   .\scripts\package-for-share.ps1 -OutputDir D:\share\autorun-mxd -Zip
#   .\scripts\package-for-share.ps1 -KeepLargeModels

param(
    [string]$OutputDir = "",
    [switch]$Zip,
    [switch]$KeepLargeModels,
    [switch]$KeepFarmMaps
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not $OutputDir) {
    $OutputDir = Join-Path (Split-Path -Parent $Root) "autorun-mxd-share"
}

$ExcludeDirNames = @(
    ".git", ".idea", "build", "resources", "AutoGo", "autogo", ".gocache", "scripts"
)

$ExcludeFileNames = @(
    "bench_gm_patrol_ai.exe",
    "default.json"
)

# Exact personal farm_map basenames to drop (generic maps are kept).
$ExcludeFarmMapFiles = @(
    "farm_map_langligelang001.json"
)

function Test-ExcludedFarmMap {
    param([string]$LeafName)
    if ($LeafName -match '001') { return $true }
    foreach ($f in $ExcludeFarmMapFiles) {
        if ($LeafName -eq $f) { return $true }
    }
    # Unicode markers in filename without non-ASCII in script source
    $markers = @(
        ([string][char]0x6D6A + [char]0x91CC + [char]0x4E2A + [char]0x6D6A),
        ([string][char]0x91CE + [char]0x718A),
        ([string][char]0x53F6 + [char]0x79CB),
        ([string][char]0x73CD + [char]0x73CD + [char]0x5976 + [char]0x8336),
        ([string][char]0x65F6 + [char]0x5C1A + [char]0x5927 + [char]0x9053)
    )
    foreach ($m in $markers) {
        if ($LeafName.Contains($m)) { return $true }
    }
    return $false
}

function Test-ExcludedPath {
    param([string]$RelativePath)
    $parts = $RelativePath -split '[\\/]'
    foreach ($part in $parts) {
        if ($ExcludeDirNames -contains $part) { return $true }
    }
    $name = Split-Path -Leaf $RelativePath
    if ($ExcludeFileNames -contains $name) { return $true }
    if (-not $KeepLargeModels) {
        if ($RelativePath -match '(?i)assets[\\/](yolo|huashu[\\/]mouse)[\\/].*\.bin$') { return $true }
        if ($RelativePath -match '(?i)[\\/]resources[\\/]') { return $true }
    }
    if (-not $KeepFarmMaps -and $RelativePath -match '(?i)assets[\\/]config[\\/]farm_map_.*\.json$') {
        $leaf = Split-Path -Leaf $RelativePath
        if (Test-ExcludedFarmMap $leaf) { return $true }
    }
    return $false
}

function Sanitize-SourceFile {
    param([string]$FilePath)
    $content = Get-Content -LiteralPath $FilePath -Raw -Encoding UTF8
    $changed = $false

    $replacements = @(
        @{
            Pattern = 'dingTalkCaptchaWebhookDefault = "https://oapi\.dingtalk\.com/robot/send\?access_token=[^"]*"'
            Replace = 'dingTalkCaptchaWebhookDefault = ""'
        },
        @{
            Pattern = 'AccessKeyID:\s+"LTAI[^"]*"'
            Replace = 'AccessKeyID:     ""'
        },
        @{
            Pattern = 'AccessKeySecret:\s+"J3j[^"]*"'
            Replace = 'AccessKeySecret: ""'
        }
    )

    foreach ($r in $replacements) {
        if ($content -match $r.Pattern) {
            $content = $content -replace $r.Pattern, $r.Replace
            $changed = $true
        }
    }

    if ($changed) {
        [System.IO.File]::WriteAllText($FilePath, $content, (New-Object System.Text.UTF8Encoding $false))
    }
}

Write-Host "Source: $Root"
Write-Host "Output: $OutputDir"
Write-Host ""

if (Test-Path $OutputDir) {
    Write-Host "Removing existing output..."
    Remove-Item -LiteralPath $OutputDir -Recurse -Force
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$copied = 0
$skipped = 0

Get-ChildItem -LiteralPath $Root -Recurse -File | ForEach-Object {
    $rel = $_.FullName.Substring($Root.Length).TrimStart('\', '/')
    if (Test-ExcludedPath $rel) {
        $script:skipped++
        return
    }
    $dest = Join-Path $OutputDir $rel
    $destDir = Split-Path -Parent $dest
    if (-not (Test-Path $destDir)) {
        New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    }
    Copy-Item -LiteralPath $_.FullName -Destination $dest -Force
    $script:copied++
}

$exampleConfig = Join-Path $Root "assets\config\default.json.example"
$destConfig = Join-Path $OutputDir "assets\config\default.json"
if (Test-Path $exampleConfig) {
    Copy-Item -LiteralPath $exampleConfig -Destination $destConfig -Force
    Write-Host "Wrote sanitized assets/config/default.json"
}

$readmePath = Join-Path $OutputDir "SHARE_README.txt"
$readmeLines = @(
    "# Share package notes",
    "",
    "Generated by scripts/package-for-share.ps1",
    "",
    "Removed:",
    "- .git / .idea / build / resources and other large dirs",
    "- assets/config/default.json secrets (use default.json.example)",
    "- personal farm_map configs (use -KeepFarmMaps to keep all)",
    "",
    "Setup:",
    "1. Fill assets/config/default.json with your own keys",
    "2. Provide yolo/huashu .bin models if excluded (-KeepLargeModels)",
    "3. Configure AutoGo local replace per go.mod",
    "",
    "Account/password are runtime-only via /login UI, not in source."
)
[System.IO.File]::WriteAllLines($readmePath, $readmeLines, (New-Object System.Text.UTF8Encoding $false))

@(
    (Join-Path $OutputDir "core\dingtalk_captcha.go"),
    (Join-Path $OutputDir "util\oss.go")
) | ForEach-Object {
    if (Test-Path $_) { Sanitize-SourceFile $_ }
}

$totalBytes = (Get-ChildItem -LiteralPath $OutputDir -Recurse -File | Measure-Object -Property Length -Sum).Sum
$totalMB = [math]::Round($totalBytes / 1MB, 1)
Write-Host ""
Write-Host ("Done: copied $copied files, skipped $skipped files")
Write-Host ("Output size: $totalMB MiB")

if ($Zip) {
    $zipPath = "$OutputDir.zip"
    if (Test-Path $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
    Compress-Archive -LiteralPath $OutputDir -DestinationPath $zipPath -CompressionLevel Optimal
    $zipMB = [math]::Round((Get-Item $zipPath).Length / 1MB, 1)
    Write-Host ("Zip: $zipPath ($zipMB MiB)")
}

Write-Host ""
Write-Host "Before sharing, scan for leftover secrets:"
Write-Host "  Select-String -Path '$OutputDir\*' -Pattern 'sk-|LTAI|access_token=' -Recurse"
